### ISSUE TITLE
Idea for new script

### ISSUE THREAD

**Issue by MrChuck007** [rhmaxdotorg/downloadable-data-pulsechain#1]
I think it would be cool to have a script that could see how all the liquidity pools connected to a single token change in price after a large purchase/sell. For example if 170,000 eth from etherium was traded for pulsechain. How high would the prices of everything else connected to pulsechain through liquidity bonding also raise (so like plsx, Inc, hex, pdai, ptgc, etc...). It would be a very fun and bullish tool to play around with to get an estimate for the price impact a huge whale buy could have on the whole system. Not sure if an oracle is needed to grab the data from different DEXs. Even a simpler version that just grabbed pulsex v1/v2 LP could give a nice ballpark guess.  I don't think there is anything on Etherium that does this yet or if it's possible to calculate the full network effect.

**Comment by rhmaxdotorg** [comment]
Hmm that sounds more like a simulation tool vs based on getting data from blockchain resources, correct me if I'm misinterpreting it. Could be interesting.

If so, sounds like it would look something like this:
- Grab liquidity pools for a coin
- Simulate big trades for that coin
- Show how liquidity pools change based on a few example big trades

Follow-up: what data would you expect to come from it? Just examples of what happens when big trades occur with current liquidity situation for a coin?

**Comment by MrChuck007** [comment]
Yes, basically a Heart's Law simulator that calculates the network effect on other coins price tied to it in LP effected by a buy/sell. Like if I make a trade on PulseX, I can only see the slippage between the two pairs I'm trading. I can't calculate how a buy in Pulsechain using wEth will raise the price of everything else paired with PLS. 

It would be cool if the UI allowed you to type in a specific token name/contract address to see the direct impact to help sort through the data.

Ultimately, instead of people speculating that their coins "will do this many x's" this cycle they can see the calculations of what a million dollar purchase will have on the ecosystem. A rising tide raises all ships and this tool will figure out how much everyone's coins are afloat hypothetically. 

Trying to calculate it by hand is too complex. It just sounds like a bullish marketing tool that would be useful for predictive technical analysis and handy for content creators.

**Comment by rhmaxdotorg** [comment]
I think we'll see something from CryptoKong as discussed on stream. Stay tuned on the repo :)

Thanks for the suggestion @MrChuck007!
